INSERT INTO `vehicle_category`(`name`, `desc`, `active`) VALUES ('bicicleta','semDescPorEnquanto',1);
INSERT INTO `vehicle_category`(`name`, `desc`, `active`) VALUES ('ciclomotor','semDescPorEnquanto',1);
INSERT INTO `vehicle_category`(`name`, `desc`, `active`) VALUES ('motoneta','semDescPorEnquanto',1);
INSERT INTO `vehicle_category`(`name`, `desc`, `active`) VALUES ('motocicleta','semDescPorEnquanto',1);
INSERT INTO `vehicle_category`(`name`, `desc`, `active`) VALUES ('triciclo','semDescPorEnquanto',1);
INSERT INTO `vehicle_category`(`name`, `desc`, `active`) VALUES ('quadriciclo','semDescPorEnquanto',1);
INSERT INTO `vehicle_category`(`name`, `desc`, `active`) VALUES ('automóvel','semDescPorEnquanto',1);
INSERT INTO `vehicle_category`(`name`, `desc`, `active`) VALUES ('microônibus','semDescPorEnquanto',1);
INSERT INTO `vehicle_category`(`name`, `desc`, `active`) VALUES ('ônibus','semDescPorEnquanto',1);
INSERT INTO `vehicle_category`(`name`, `desc`, `active`) VALUES ('bonde','semDescPorEnquanto',1);
INSERT INTO `vehicle_category`(`name`, `desc`, `active`) VALUES ('reboque ou semi-reboque','semDescPorEnquanto',1);
INSERT INTO `vehicle_category`(`name`, `desc`, `active`) VALUES ('charrete','semDescPorEnquanto',1);
INSERT INTO `vehicle_category`(`name`, `desc`, `active`) VALUES ('caminhonete','semDescPorEnquanto',1);
INSERT INTO `vehicle_category`(`name`, `desc`, `active`) VALUES ('caminhão','semDescPorEnquanto',1);
INSERT INTO `vehicle_category`(`name`, `desc`, `active`) VALUES ('carroça','semDescPorEnquanto',1);
INSERT INTO `vehicle_category`(`name`, `desc`, `active`) VALUES ('carro-de-mão','semDescPorEnquanto',1);
INSERT INTO `vehicle_category`(`name`, `desc`, `active`) VALUES ('camioneta','semDescPorEnquanto',1);
INSERT INTO `vehicle_category`(`name`, `desc`, `active`) VALUES ('utilitário','semDescPorEnquanto',1);
INSERT INTO `vehicle_category`(`name`, `desc`, `active`) VALUES ('outros','semDescPorEnquanto',1);
INSERT INTO `vehicle_category`(`name`, `desc`, `active`) VALUES ('caminhão-trator','semDescPorEnquanto',1);
INSERT INTO `vehicle_category`(`name`, `desc`, `active`) VALUES ('trator de rodas','semDescPorEnquanto',1);
INSERT INTO `vehicle_category`(`name`, `desc`, `active`) VALUES ('trator de esteiras','semDescPorEnquanto',1);
INSERT INTO `vehicle_category`(`name`, `desc`, `active`) VALUES ('trator misto','semDescPorEnquanto',1);